# Define the basic settings of the site 
site:
  title: FRIDA
  # The 404 page and sitemap files only get generated when the url property is set 
  start_page: component-pension:de/PensionService.adoc


# Define the components which should be included in the site
content:
  sources:
  - url: https://github.com/FRIDA-official/Antora-PensionService
    branches: [master, 1.1]
    start_path: docs

# The ui defines the layout of the website. You can find the default ui under https://gitlab.com/antora/antora-ui-default
# After you fork the repository you can make change it to fit your needs.
ui:
  bundle:
    url: https://github.com/FRIDA-official/Antora-UI/raw/master/build/ui-bundle.zip
    snapshot: true
  